### ISSUE TITLE
[FULL COVERAGE] test: Improve coverage of _get_clickable in /scrapy/http/request/form.py

### ISSUE THREAD

**Issue by fredrikfloven** [dd2480-2019-group13/scrapy#16]
_get_clickable() has 12 CCN
![image](https://user-images.githubusercontent.com/40166249/53004586-c8e4f200-3431-11e9-815e-231cbe013c72.png)

the module form.py which contain _get_clickable has 97% ***test*** and ***branch*** coverage
![image](https://user-images.githubusercontent.com/40166249/53004475-91764580-3431-11e9-9b2d-b3237e12dd72.png)

**Comment by lilfelix** [comment]
Closed due to assignment 3 being finished.
We improved coverage for other functions in the end.
