### ISSUE TITLE
[PROBLEMATIC] test: improve coverage for csviter in scrapy/utils/iterators.py

### ISSUE THREAD

**Issue by fredrikfloven** [dd2480-2019-group13/scrapy#33]
97% coverage according to coverage.py

![image](https://user-images.githubusercontent.com/40166249/53019511-2fc7d280-3455-11e9-9463-a207bbd4b48c.png)

![image](https://user-images.githubusercontent.com/40166249/53019531-3d7d5800-3455-11e9-8f56-80635fe924bd.png)

**Comment by fredrikfloven** [comment]
Line 109 requires testing with python2
There exists a test for line 119-120, but it doesn't seem to actually work

**Comment by lilfelix** [comment]
Closed due to assignment 3 being finished.
We improved coverage for other functions in the end.
