### ISSUE TITLE
[PROBLEMATIC] test: improve coverage for _link_allowed in scrapy/linkextractors/__init__.py

### ISSUE THREAD

**Issue by annaekli** [dd2480-2019-group13/scrapy#7]
- branch coverage 21%

**Comment by annaekli** [comment]
- branch coverage after adding unittest for _link_allowed() measured with coverage.py: 20%
- branch coverage after adding unittest for _link_allowed() measured with own branch coverage tool: 100%

Thus, __init__.py in linkextractors does not seem to be included at all when running coverage.py run --branch. Leaves this issue for now.

**Comment by lilfelix** [comment]
Closed due to assignment 3 being finished.
We improved coverage for other functions in the end.
